# Header
menu:
  首页:
  特性: feature
  文档: doc
  下载: download
  关于: about

rss: /saber/atom.xml
favicon: /saber/favicon.png
github: https://github.com/ecomfe/saber

# Content
excerpt_link: 阅读全文
duoshuo_shortname: saberjs

# Sidebar
# sidebar: right
# widgets:
# - category
# - tag
# - tagcloud
# - archive
# - recent_posts

# Miscellaneous
# google_analytics:
# twitter:
# google_plus:
# fb_admins:
# fb_app_id:
